# Generated by Django 6.0.2 on 2026-03-06 15:08

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auths", "0001_initial"),
        ("base", "__first__"),
        ("parameters", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestStatus",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
            ],
            options={
                "verbose_name": "Estado de Solicitud",
                "verbose_name_plural": "Estados de Solicitud",
                "db_table": "operative_requeststatuses",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OperativeRequest",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(verbose_name="Número de Solicitud")),
                ("value", models.IntegerField(verbose_name="Valor")),
                (
                    "assigned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Asignación"
                    ),
                ),
                (
                    "assigned_by",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Asignado por",
                    ),
                ),
                (
                    "observations",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Creado por"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Fecha Actualización"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Validación"
                    ),
                ),
                (
                    "validated_by",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Validado por",
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.applicant",
                        verbose_name="Solicitante",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auths.account",
                        verbose_name="Asignado a",
                    ),
                ),
                (
                    "ramo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parameters.ramo",
                        verbose_name="Ramo",
                    ),
                ),
                (
                    "taker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.taker",
                        verbose_name="Tomador",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operative.requeststatus",
                        verbose_name="Estado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud",
                "verbose_name_plural": "Solicitudes",
                "db_table": "operative_operativerequests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OperativeRequestDocument",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="Nombre Archivo"),
                ),
                (
                    "file_type",
                    models.CharField(max_length=255, verbose_name="Tipo Archivo"),
                ),
                ("content", models.TextField(verbose_name="Contenido Base64")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Creado por"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Fecha Actualización"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "document_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parameters.documentclass",
                        verbose_name="Clase de Documento",
                    ),
                ),
                (
                    "operative_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operative.operativerequest",
                        verbose_name="Solicitud",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Solicitud",
                "verbose_name_plural": "Documentos de Solicitud",
                "db_table": "operative_requestdocuments",
                "ordering": ["operative_request", "document_class"],
            },
        ),
        migrations.CreateModel(
            name="RequestFieldValue",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255, verbose_name="Valor")),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parameters.ramofield",
                        verbose_name="Campo",
                    ),
                ),
                (
                    "operative_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operative.operativerequest",
                        verbose_name="Solicitud",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor de Campo de Solicitud",
                "verbose_name_plural": "Valores de Campos de Solicitud",
                "db_table": "operative_requestfieldvalues",
                "ordering": ["operative_request", "field"],
            },
        ),
        migrations.CreateModel(
            name="RequestEvent",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observations",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Creado por"
                    ),
                ),
                (
                    "operative_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operative.operativerequest",
                        verbose_name="Solicitud",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="operative.requeststatus",
                        verbose_name="Estado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de Solicitud",
                "verbose_name_plural": "Eventos de Solicitud",
                "db_table": "operative_requestevents",
                "ordering": ["created_at"],
            },
        ),
    ]
