# Generated by Django 6.0.2 on 2026-02-21 19:46

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "capital_code",
                    models.CharField(
                        blank=True,
                        max_length=2,
                        null=True,
                        verbose_name="Código de la Capital",
                    ),
                ),
            ],
            options={
                "verbose_name": "País",
                "verbose_name_plural": "Países",
                "db_table": "localization_countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=2, verbose_name="Código")),
                (
                    "short",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="Nombre Corto"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "capital_code",
                    models.CharField(
                        blank=True,
                        max_length=2,
                        null=True,
                        verbose_name="Código Capital",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="localization.country",
                        verbose_name="País",
                    ),
                ),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
                "db_table": "localization_states",
                "ordering": ["country", "name"],
                "unique_together": {("country", "code")},
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=2, verbose_name="Código")),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="localization.country",
                        verbose_name="País",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="localization.state",
                        verbose_name="Departamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ciudad",
                "verbose_name_plural": "Ciudades",
                "db_table": "localization_cities",
                "ordering": ["country", "state", "code"],
                "unique_together": {("country", "code")},
            },
        ),
    ]
