# Generated by Django 6.0.2 on 2026-03-06 16:23

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentClassType",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
            ],
            options={
                "verbose_name": "Tipo de Documento",
                "verbose_name_plural": "Tipos de Documentos",
                "db_table": "parameters_documentclasstypes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FieldType",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
            ],
            options={
                "verbose_name": "Tipo de Campo",
                "verbose_name_plural": "Tipos de Campos",
                "db_table": "parameters_fieldtypes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Ramo",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Creado por"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Creado por"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ramo",
                "verbose_name_plural": "Ramos",
                "db_table": "parameters_ramos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentClass",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Creado por"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Creado por"
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parameters.documentclasstype",
                        verbose_name="Tipo de Documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clase de Documento",
                "verbose_name_plural": "Clases de Documentos",
                "db_table": "parameters_documentclasses",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RamoField",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Título"
                    ),
                ),
                (
                    "mandatory",
                    models.BooleanField(default=False, verbose_name="Es Obligatorio"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Creado por"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Creado por"
                    ),
                ),
                (
                    "field_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parameters.fieldtype",
                        verbose_name="Tipo de Campo",
                    ),
                ),
                (
                    "ramo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parameters.ramo",
                        verbose_name="Ramo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campo de Ramo",
                "verbose_name_plural": "Campos de Ramos",
                "db_table": "parameters_ramofields",
                "ordering": ["name"],
                "unique_together": {("ramo", "name")},
            },
        ),
        migrations.CreateModel(
            name="FieldOption",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=50, verbose_name="Valor")),
                ("title", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parameters.ramofield",
                        verbose_name="Campo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opción de Campo",
                "verbose_name_plural": "Opciones de Campos",
                "db_table": "parameters_fieldoptions",
                "ordering": ["field", "title"],
                "unique_together": {("field", "value")},
            },
        ),
        migrations.CreateModel(
            name="RamoRequiredDocument",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mandatory",
                    models.BooleanField(default=False, verbose_name="Es Obligatorio"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Creado por"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Creado por"
                    ),
                ),
                (
                    "document_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parameters.documentclass",
                        verbose_name="Clase de Documento",
                    ),
                ),
                (
                    "ramo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parameters.ramo",
                        verbose_name="Ramo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Requerido para Ramo",
                "verbose_name_plural": "Documentos Requeridos para Ramos",
                "db_table": "parameters_ramorequireddocuments",
                "ordering": ["ramo", "document_class"],
                "unique_together": {("ramo", "document_class")},
            },
        ),
    ]
